---

- name: Install Dependencies in apt repo
  apt:
    name: "{{ item }}"
  with_items:
    - fastqc
    - parallel
    - bowtie2
    - fastx-toolkit
    - cpanminus

- name: Get the Fork Manager Perl module
  command: cpanm Parallel::ForkManager
